# Generated by Django 5.2.5 on 2025-08-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_registration_delete_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('sub_topic_name', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='admin_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('sub_topic_name', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
