# Generated by Django 5.2.5 on 2025-09-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_mcq_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='correct_answer',
            field=models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], max_length=1),
        ),
    ]
