# Generated by Django 5.2.5 on 2025-09-10 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_mcq_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('subtopic', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('date_attempted', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_questions', models.IntegerField()),
                ('correct_questions', models.IntegerField()),
                ('wrong_questions', models.IntegerField()),
                ('score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.registration')),
            ],
        ),
    ]
