# Generated by Django 5.2.5 on 2025-09-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_quizresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminContent',
        ),
        migrations.DeleteModel(
            name='UserContent',
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterModelTable(
            name='mcq',
            table='base_mcq',
        ),
    ]
