# Generated by Django 5.2.5 on 2025-09-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_admincontent_delete_usercontent_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mcq',
            table=None,
        ),
    ]
